version: '2'
services:
    brooklyn-app:
        image: brooklyn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://brooklyn-mysql:3306/brooklyn?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    brooklyn-mysql:
        extends:
            file: mysql.yml
            service: brooklyn-mysql
